WeatherForecastApp/Models/OpenWeatherMap.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeatherForecastApp.Models
{
    public class OpenWeatherMap
    {
        public string ApiResponse { get; set; }

        public Dictionary<string, string> Cities { get; set; }
    }
}

WeatherForecastApp/Controllers/OpenWeatherMapController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WeatherForecastApp.Models;

namespace WeatherForecastApp.Controllers
{
    public class OpenWeatherMapController : Controller
    {
        private const string API_KEY = "fd0e89d7a36bfb826d77fbd9deab5935";

        // GET: OpenWeatherMapMvc
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Get data about current weather condition by city id using the HTTP request from OpenWeatherAPI.  
        /// </summary>
        /// <param name="cityId">OpenWeatheAPI city Id</param>
        /// <returns>Current weather data in json format.</returns>
        [HttpGet]
        [Route("weather/{cityId?}")]
        public JsonResult GetWeatherDataByCityId(string cityId)
        {
            var response = new ResponseViewModel();

            if (cityId != null)
            {
                HttpWebRequest apiRequest = WebRequest.Create("http://api.openweathermap.org/data/2.5/weather?id=" +
                                                                cityId + "&appid=" + API_KEY + "&units=metric") as HttpWebRequest;

                string apiResponse;
                using (HttpWebResponse httpResponse = apiRequest.GetResponse() as HttpWebResponse)
                {
                    StreamReader reader = new StreamReader(httpResponse.GetResponseStream());
                    apiResponse = reader.ReadToEnd();
                }

                var weatherData = JsonConvert.DeserializeObject<ResponseWeatherModel>(apiResponse);

                response.Message = "Weather data for " + weatherData.Name + " received successfully!";
                response.Data = weatherData;
                response.Error = false;
            }
            else
            {
                response.Message = "No city id received";
                response.Error = true;
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Get data about weather condition for 5 days by city id using the HTTP request from OpenWeatherAPI.
        /// </summary>
        /// <param name="cityId">OpenWeatheAPI city Id</param>
        /// <returns>5 days forecast weather data in json format.</returns>
        [HttpGet]
        [Route("weather2/{cityId?}")]
        public JsonResult GetForecastWeatherDataByCityId(string cityId)
        {
            var response = new ResponseViewModel();

            if (cityId != null)
            {
                HttpWebRequest apiRequest = WebRequest.Create("http://api.openweathermap.org/data/2.5/forecast?id=" +
                                                               cityId + "&appid=" + API_KEY + "&units=metric") as HttpWebRequest;

                string apiResponse;
                using (HttpWebResponse httpResponse = apiRequest.GetResponse() as HttpWebResponse)
                {
                    StreamReader reader = new StreamReader(httpResponse.GetResponseStream());
                    apiResponse = reader.ReadToEnd();
                }

                var weatherData = JsonConvert.DeserializeObject<FiveDayWeatherForecastModel>(apiResponse);

                response.Message = "Weather data for " + weatherData.City + " received successfully!";
                response.Data = weatherData;
                response.Error = false;
            }
            else
            {
                response.Message = "No city id received";
                response.Error = true;
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

WeatherForecastApp/Views/OpenWeatherMap/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Open Weather API</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Open Weather API", "Index", "OpenWeatherMap", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        <div id="home-page" class="page active">
            <div class="container-fluid">
                <div class="jumbotron">
                    <h3 class="display-3">
                        Get weather by city name
                    </h3>
                    <hr class="my-4">
                    <form>
                        <div class="form-group">
                            <label for="cityNameDd">City Name</label>
                            <input type="text" id="cityNameInput" placeholder="Example: Kiev" class="hidden">
                            <select id="cityNameDd">
                                <option value="7839805">Melbourne</option>
                                <option value="2193734">Auckland</option>
                                <option value="292968">Abu Dhabi</option>
                                <option value="564719">Dubna</option>
                                <option value="1270000">Hodal</option>
                                <option value="546633">Kokorevka</option>
                                <option value="518346">Novopetrovskoye</option>
                                <option value="553514">Kamennomostskiy</option>
                                <option value="698740">Odessa</option>
                                <option value="707244">Kakhovka</option>
                                	
                            </select>
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="button" id="getWeather" value="Get weather">
                            <input class="btn btn-primary" type="button" id="getForecast" value="Get forecast">
                        </div>
                    </form>
                </div>

                <div class="jumbotron hidden" id="weatherToday">
                    <h1 class="display-3">Weather in <span class="cityName" ></span>, <span class="countryName" ></span></h1>
                    <hr class="my-4">
                    <img src="" id="weatherIcon" />
                    <p class="lead">
                        Temp: <span id="mainTemp"></span>°C, <span id="weatherMain"></span> (<span id="weatherDescription"></span>)
                    </p>
                </div>
                
                <div class="jumbotron hidden" id="weatherForecast">
                    <h1 class="display-3">Weather Forecast in <span class="cityName"></span>, <span class="countryName"></span> for 5 days</h1>
                    <hr class="my-4" />
                    <div class="row" id="weatherForecastRowContainer">
                        
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script id="hidden-template" type="text/x-custom-template">
        <div class="col-md-1 col-xs-1">
            <div class="thumbnail text-center">
                <h4>{DATE_TIME}</h4>
                <img src="http://openweathermap.org/img/w/{ICON}.png">
                <div class="caption">
                    <p><span>{TEMPERATURE}°C</span></p>
                    <p><span>{WIND_SPEED} m/s</span></p>
                    <p><span>{PRESSURE}</span></p>
                </div>
            </div>
        </div>
    </script>
    <script type="text/javascript">
        var getWeatherUrl = "@Url.Action("GetWeatherDataByCityId", "OpenWeatherMap")";
        var getForecastUrl = "@Url.Action("GetForecastWeatherDataByCityId", "OpenWeatherMap")";
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/eventHandlers.js" type="text/javascript"></script>
</body>
</html>